name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Test and tidy
        run: |
          go mod tidy
          go get .
          go test ./...
          gofmt -l
      - name: Publish Go module
        env:
          TAG: ${{ github.ref_name }}
        run: |
          go list -m github.com/jesperkha/gokenizer@$TAG
